name: "TechCore Action"
description: "Deploy your application to the TechCore platform"
inputs:
  techcore-api-key: # id of input
    description: "API Key from the TechCore Platform"
    required: true
  hostname: # id of input
    description: "The TechCore Environment you want to target"
    required: true
  docker-args: # id of input
    description: "The TechCore Environment you want to target"
    required: false
  image-repo-name: # id of input
    description: "ECR Repository to use"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Create repo if doesnt exist
      continue-on-error: true
      shell: bash
      run: |
        aws ecr create-repository --repository-name ${{inputs.image-repo-name}} --region us-east-1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 930245254249.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: ${{ inputs.image-repo-name }}
        IMAGE_TAG: ${{ github.sha }}
      shell: bash
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ${{inputs.docker-args}} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Deploy built image to specified TechCore Namespace
      uses: TechCore-Rex/gh-action@latest
      with:
        techcore-api-key: ${{ inputs.techcore-api-key }}
        hostname: ${{ inputs.hostname }}
        image: 930245254249.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.image-repo-name }}:${{ github.sha }}
