name: "TechCore Action"
description: "Deploy your application to the TechCore platform"
inputs:
  techcore-api-key: # id of input
    description: "API Key from the TechCore Platform"
    required: true
  environment: # id of input
    description: "The TechCore Environment you want to target"
    required: true
  docker-args: # id of input
    description: "The TechCore Environment you want to target"
    required: false
  image-repo-name: # id of input
    description: "ECR Repository to use"
    required: true
runs:
  using: "composite"
  steps:
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REPOSITORY: ${{ inputs.image-repo-name }}
        IMAGE_TAG: ${{ github.sha }}
      shell: bash
      run: |
        docker build -t $ECR_REPOSITORY/$ECR_REPOSITORY:$IMAGE_TAG ${{ input.docker-args }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
